version: '3.9'
services:
  site:
    container_name: site
    build:
      context: site/ 
      dockerfile: Dockerfile 
    ports:
      - 5001:80
    volumes:
      - ./site:/var/www/html/
  site2:
    container_name: site2
    build:
      context: site/ 
      dockerfile: Dockerfile 
    ports:
      - 5002:80
    volumes:
      - ./site:/var/www/html/
    
  nginx:
    build:
      context: nginx/
    ports:
      - 8080:80
    depends_on:
      - site
      - site2

      

    