version: '3.9'
services:
  site:
    container_name: site
    build:
      context: site/ 
      dockerfile: Dockerfile 
    ports:
      - 5001:80
    volumes:
      - ./site:/var/www/html/
  site2:
    container_name: site2
    build:
      context: site/ 
      dockerfile: Dockerfile 
    ports:
      - 5002:80
    volumes:
      - ./site:/var/www/html/
    
  nginx:
    build:
      context: nginx/
    ports:
      - 8080:80
    depends_on:
      - site
      - site2

  db:
    image: mariadb:10.2 
    restart: always
    environment:
      MYSQL_DATABASE: lb
      MYSQL_USER: matte
      MYSQL-PASSWORD: matte
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump:/var/lib/mysql

volumes:
  db:



      

    